---
  # tasks file
  - name: Load variable file
    include_vars: emm.yml
  #- name: Create directory '{{ working_dir }}'
  #  file:
  #    path: '{{ working_dir }}'
  #    state: directory
  #    mode: '0755'
  - name: Get EM Installation Tool version
    shell: ls -td {{ working_dir }}/CXP* | head -1
    register: version
  - name: Give full permissions to /var/opt/ to copy backup data
    shell: sudo chmod 777 /var/opt
  - name: Copy mm_backup.tar
    copy: src='/emm_upgrade/mm_backup.tar' dest=/var/opt/
  - name: Extract mm_backup.tar
    shell: sudo tar -xf mm_backup.tar; sudo chmod -R 755 /var/opt/mm_backup; sudo chown -R root:root /var/opt/mm_backup;
    args:
      chdir: '/var/opt/'
  - name: Restore permissions to /var/opt/
    shell: sudo chmod 755 /var/opt
  - name: Enabling external storage
    shell: sudo vxdctl init; sudo vxdctl enable; sudo vxdisk list
  - name: Configure Mount points - TODO verify inputs in enviroment with external storage
    shell: sudo ./configure_mountpoints.sh /var/opt/mm_backup/system/mm_mount_point_info
    args:
      chdir: '{{ version.stdout }}/upgrade/upgrade_scripts/'
  - name: Stop Logical Servers
    shell: echo "yes" |sudo MMControl stop
  - name: Create input file to Restore manager data
    shell: echo {{ mgr_db_pwd }} > /tmp/restore_manager_data.in
  - name: Restore manager data
    shell: cat /tmp/restore_manager_data.in | sudo ./upgrade_manager.sh -m local -d /var/opt/mm_backup
    args:
      chdir: '{{ version.stdout }}/upgrade/upgrade_scripts/'
  - name: Create input file to Restore fem data
    #shell: printf "{{ gui_user }}\n{{ gui_pwd }}\n{{ mgr_db_pwd }}\n{{ Server1_db_pwd }}\n{{ Server2_db_pwd }}\n{{ Server3_db_pwd }}\n{{ Server4_db_pwd }}\n{{ FTF_db_pwd }}\n{{ mmeftf1_db_pwd }}\n" > /tmp/restore_fem_data.in
    shell: printf "{{ gui_user }}\n{{ gui_pwd }}\n{{ mgr_db_pwd }}\n{{ Server1_db_pwd }}\n{{ Server2_db_pwd }}\n{{ Server3_db_pwd }}\n" > /tmp/restore_fem_data.in    
  - name: Restore fem data
    shell: cat /tmp/restore_fem_data.in | sudo ./upgrade_fem.sh -m local -d /var/opt/mm_backup
    args:
      chdir: '{{ version.stdout }}/upgrade/upgrade_scripts/'
  - name: Create input file to Restore olm data
    shell: echo {{ SERVER_db_pwd }} > /tmp/restore_olm_data.in
  - name: Restore olm data
    shell: cat /tmp/restore_olm_data.in | sudo ./upgrade_olm.sh -m local -d /var/opt/mm_backup
    args:
      chdir: '{{ version.stdout }}/upgrade/upgrade_scripts/'
