---
  # tasks file
  - name: Load enviroment file
    include_vars: ../ENV_INFO/emm.yml
  - name: Get EM20 Installation Tool version
    shell: ls -td {{ working_dir }}/CXP* | head -1
    register: version
  
  - name: Copy EM20 Disk Group Configuration - DISK NAMES in .in should be the NEW Temporary disks exposed to EM20
    copy: src="../ENV_INFO/DISK/DG" dest={{ version.stdout }}/
  - name: Get .in files
    shell: ls ./DG/*.in
    args:
      chdir: '{{ version.stdout }}'
    register: in_file
  - name: Create Disk Groups with MM_UTILITY - check logs in /var/adm/MM_LOGS
    shell: "cat {{ item }} | sudo -E ./MM_UTILITY"
    with_items: '{{ in_file.stdout_lines}}'
    args:
      chdir: '{{ version.stdout }}'
  
  - name: Copy Cluster configuration for new Disk Groups
    copy: src="../ENV_INFO/DISK/CLUS" dest={{ version.stdout }}/
  - name: Get .in files
    shell: ls ./CLUS/*.in
    args:
      chdir: '{{ version.stdout }}'
    register: in_file
  - name: Add new Disk Groups to Cluster with MM_UTILITY - check logs in /var/adm/MM_LOGS
    shell: "cat {{ item }} | sudo -E ./MM_UTILITY"
    with_items: '{{ in_file.stdout_lines}}'
    args:
      chdir: '{{ version.stdout }}'
  