---
# tasks for veritas installation on CPS servers
- name: Load variable file
  include_vars: ../ENV_INFO/emm.yml

- name: Get EM20 Installation Tool version
  shell: ls -td {{ working_dir}}/CXP* | head -1
  register: version  

- name: Copy automation script
  copy: src=cps_install_veritas.sh dest={{ version.stdout }}/cps_install_veritas.sh mode=u+rwx

- name: Execute the Veritas Installation script
  shell: sh ./cps_install_veritas.sh {{ veritas }}
  args:
    chdir: '{{ version.stdout }}'
  ignore_errors: no
  ignore_unreachable: no
  
- name: Verifying Veritas InfoScale Software Deployment
  shell: rpm -qa | grep VRTS