---
  # tasks file for fem
  - name: Load enviroment file
    include_vars: ../../../ENV_INFO/emm.yml
  - name: Get hostname
    shell: hostname
    register: hostname
  - name: include vars specific to hostname
    include_vars:
      dir: ../../../ENV_INFO/
      files_matching: "{{ hostname.stdout }}"
  - name: Get EM20 Installation Tool version
    shell: ls -td {{ working_dir }}/CXP* | head -1
    register: version
  - name: Copy automation script
    copy: src=install_FEM_Addnode.sh dest={{ version.stdout }}/install_FEM_Addnode.sh mode=u+rwx
    when: manager == "y"
  - name: Copy automation script
    copy: src=install_FEM_Addnode_withoutMGR.sh dest={{ version.stdout }}/install_FEM_Addnode.sh mode=u+rwx
    when: manager == "n"
  - name: Execute the FEM Add node script - check logs in /var/adm/MM_LOGS/App - or connect with "screen -x DEVOPS" in master node
    shell: screen -S DEVOPS sh ./install_FEM_Addnode.sh
    args:
      chdir: '{{ version.stdout }}'  