---
# tasks file for platform_cps
- name: Load variable file
  include_vars: emm.yml
- name: Update the hostname
  hostname: name=emm1-001
  
- name: Go to template path & create platform nfs ini
  shell:
    chdir: /install/CXP9034012_R8S/templates/Linux
    cmd: cp platform_cluster_nfs.ini.eric platform_cluster_nfs.ini
- name: Copy the platform script
  copy: src=Install_Platform.sh dest=/install/CXP9034012_R8S/
- name: Copy hosts file
  copy: src=hosts dest=/etc/hosts backup=yes
- name: Update the cps ini file for ONM Bond
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cluster_nfs.ini
    section: ONM Bond
    option: bonding_interface_primary_ONM
    value: "{{ bonding_interface_primary_ONM }}"
    no_extra_spaces: yes
- name: Update the nfs ini file for Interface IP
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cluster_nfs.ini
    section: Interface IP
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {bonding_interface_ip_ONM: "{{ bonding_interface_ip_ONM }}",netmask_ONM: "{{ netmask_ONM }}",default_gateway_ip_ONM: "{{ default_gateway_ip_ONM }}"}
- name: Update the nfs ini file for CLUSTER
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cluster_nfs.ini
    section: Cluster
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {Cluster_ID: "{{ Cluster_ID }}",Cluster_Name: "{{ Cluster_Name }}",HeartBeat_Link_1: "{{ HeartBeat_Link_1 }}",HeartBeat_Link_2: "{{ HeartBeat_Link_2 }}",IO_Fencing_Type: "{{ IO_Fencing_Type }}",NFS_Server_Version_for_MMDB: "{{ NFS_Server_Version_for_MMDB }}",NFS_Share_IP_for_MMDB: "{{ NFS_Share_IP_for_MMDB }}",MMDB_NFS_Share_Name: "{{ MMDB_NFS_Share_Name }}",NFS_Server_Version_for_MMStorage: "{{ NFS_Server_Version_for_MMStorage }}",NFS_Share_IP_for_MMStorage: "{{ NFS_Share_IP_for_MMStorage }}",MMStorage_NFS_Share_Name: "{{ MMStorage_NFS_Share_Name }}",other_hosts_ONM: "{{ other_hosts_ONM }}"}
- name: Copy automation script
  copy: src=install_updated.sh dest=/opt/
- name: Copy the cps libfunc script
  copy: src=libfunc_cps_platform.sh dest=/install/CXP9034012_R8S/lib/Linux/
- name: Copy the cps text file with IPs
  copy: src=cps.txt dest=/install/CXP9034012_R8S/lib/Linux/
- name: Execute the EMM platform script
  shell: sh /opt/install_updated.sh
    
 
