---
- hosts: OPENSTACK
  gather_facts: false
  vars_files:
    - ../ENV_INFO/env.yml


  tasks:
    #- name: verify template for em creation
      #shell: |
        #source {{ sourcepath }}{{ cloud }}
        #openstack stack create -e {{ emvmenv }} --timeout 10 --dry-run -t {{ emvmdeploy }} {{ emvmstack }}
      #register: em_template_verify_output
    #- debug: var=em_template_verify_output.stdout_lines


    - name: em vm creation
      shell: |
        source {{ sourcepath }}{{ cloud }}
        openstack stack create -e {{ emvmenv }} --timeout 10 -t {{ emvmdeploy }} {{ emvmstack }}
        sleep 30s
        openstack stack show {{ emvmstack }}
      register: em_vm_creation_output
    #- debug: var=em_vm_creation_output.stdout_lines

    - name: "check CREATE_FAILED"
      when: '"CREATE_FAILED" in em_vm_creation_output.stdout'
      fail: msg="Aborting pipeline"


    - name: verify stack list
      shell: |
        source {{ sourcepath }}{{ cloud }}
        openstack stack list
      register: stack_list_output
    - debug: var=stack_list_output.stdout_lines

