---
- hosts: EMM_CPS
  gather_facts: no
  tasks:
  - name: healthcheck CPS Group
    shell: sudo /opt/VRTSvcs/bin/hastatus -sum
    register: status
  - name: healthcheck status
    assert:
      that:
        - status.stdout is search('ONLINE')
      success_msg: "CPS is working fine"
      fail_msg: "CPS is NOT working fine, please check before proceeding."
  - name: IMPORTANT MESSAGE
    debug:
      msg: "Remember to configure MANUALLY the password-less connectiviy from EMM Nodes towards all CPS VIPs"