---
  - hosts: emm_worker
    tasks:
    - name: healthcheck EMM worker Group
      shell: sudo /opt/VRTSvcs/bin/hastatus -sum
      register: status
    - name: healthcheck status
      debug:
        msg: "EMM worker is working fine"
      when: status.stdout is search('RUNNING')  