---
- hosts: EMM_CPS3
  tasks:
  - name: healthcheck CPS3 Group
    shell: hastatus -sum
    register: status
  - name: healthcheck status
    debug:
      msg: "CPS3 is working fine"
    when: status.stdout is search('ONLINE')
