---
- hosts: emm_master
  tasks:
  - name: OnlineServer status
    shell: sudo /usr/bin/MMControl status | grep OnlineServer
    register: OnlineServer
  - name: om_db_SERVER status
    shell: sudo /usr/bin/MMControl status | grep om_db_SERVER
    register: om_db_SERVER
  - name: Tracer status
    shell: sudo /usr/bin/MMControl status | grep Tracer
    register: Tracer
  - name: om_db_Tracer status
    shell: sudo /usr/bin/MMControl status | grep om_db_Tracer
    register: om_db_Tracer

  - name: healthcheck status
    assert:
      that:
        - OnlineServer.stdout is search('ONLINE')
        - om_db_SERVER.stdout is search('ONLINE')
        - Tracer.stdout is search('ONLINE')
        - om_db_Tracer.stdout is search('ONLINE')
      success_msg: "OLM App installed successfully"
      fail_msg: "OLM App is NOT working fine, please check before proceeding."