---
- hosts: emm_master
  tasks:
  - name: fm_db_Server1 status
    shell: sudo /usr/bin/MMControl status | grep fm_db_Server1
    register: femstatus
  
  - name: healthcheck status
    debug:
      msg: "FEM App installaed successfully"
    when: 
      - femstatus.stdout is search('ONLINE')
      