---
- hosts: emm_master
  gather_facts: no
  tasks:
  - name: fm_db_Server1 status
    shell: sudo /usr/bin/MMControl status | grep fm_db_Server1
    register: femstatus
  
  - name: healthcheck status
    assert:
      that:
        - femstatus.stdout is search('ONLINE')
      success_msg: "FEM App installed successfully"
      fail_msg: "FEM App is NOT working fine, please check before proceeding."

      