---
- hosts: emm_worker
  # serial = 1 to add workers sequencially, and not in parallel which will cause VCS conflicts
  serial: 1
  roles:
    - role: ../ROLES/platform_emm_addnode
      ignore_errors: no
