---
  - hosts: emm_worker
    gather_facts: no
    tasks:
    - name: healthcheck EM Worker Group
      shell: sudo /opt/VRTSvcs/bin/hastatus -sum
      register: status
    
    - name: healthcheck status
      assert:
        that:
          - status.stdout is search('RUNNING')
        success_msg: "EM Worker is working fine"
        fail_msg: "EM Worker is NOT working fine, please check before proceeding."
