---
- hosts: emm_master
  tasks:
  - name: CLI status
    shell: sudo /usr/bin/MMControl status | grep CLI
    register: clistatus
  - name: NodeManager status
    shell: sudo /usr/bin/MMControl status | grep NodeManager
    register: NodeManager
  - name: Manager status
    shell: sudo /usr/bin/MMControl status | grep Manager
    register: Manager
  - name: Database status
    shell: sudo /usr/bin/MMControl status | grep Database
    register: Database
  - name: Sentinel status
    shell: sudo /usr/bin/MMControl status | grep Sentinel
    register: Sentinel
  - name: Tomcat status
    shell: sudo /usr/bin/MMControl status | grep Tomcat
    register: Tomcat
  - name: healthcheck status
    assert:
      that:
        - clistatus.stdout is search('ONLINE')
        - NodeManager.stdout is search('ONLINE')
        - Manager.stdout is search('ONLINE')
        - Database.stdout is search('ONLINE')
        - Sentinel.stdout is search('ONLINE')
        - Tomcat.stdout is search('ONLINE')
      success_msg: "MGR App installed successfully"
      fail_msg: "MGR App is NOT working fine, please check before proceeding."
