---
- hosts: EMM_CPS,emm_master,emm_worker
  become: yes
  #sudo: yes
  #remote_user: "{{user}}"
  #vars_files:
  #  - ../ENV_INFO/emm.yml
  roles:
    - role: ../ROLES/apply_ospatches
      ignore_errors: no

