stages:
  - COPY-REPO-TO-DDS 
  - EM-FLAVOR-CREATION
  - EM-UPLOAD-IMAGE
  - TENANT-RESOURCE-CREATION
  - SERVER-GROUP-CREATION
  - EM-VM-CREATION


COPY-REPO-TO-DDS:
  stage: COPY-REPO-TO-DDS
  tags:
    - emm-stc
  script:
    - hostname
    - pwd
    - ssh root@dds_stc 'hostname'
    - ssh root@dds_stc 'mkdir -p ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}'
    - scp -pr ./ENV_INFO/ ./HOST/ ./PLAYBOOK/ root@dds_stc:./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}
  #allow_failure: true
  when: manual

EM-FLAVOR-CREATION:
  stage: EM-FLAVOR-CREATION
  tags:
    - emm-stc
  script:
    - ssh root@dds_stc ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/em-flavor-creation.yml -v
  allow_failure: true
  when: manual

EM-UPLOAD-IMAGE:
  stage: EM-UPLOAD-IMAGE
  tags:
    - emm-stc
  script:
    - ssh root@dds_stc ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/em-upload-image.yml -v
  allow_failure: true
  when: manual
  
TENANT-RESOURCE-CREATION:
  stage: TENANT-RESOURCE-CREATION
  tags:
    - emm-stc
  script:
    - ssh root@dds_stc ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/tenant-resource-creation.yml -v
  allow_failure: true
  when: manual  
 
SERVER-GROUP-CREATION:
  stage: SERVER-GROUP-CREATION
  tags:
    - emm-stc
  script:
    - ssh root@dds_stc ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/server-group-creation.yml -v
  allow_failure: true
  when: manual

EM-VM-CREATION:
  stage: EM-VM-CREATION
  tags:
    - emm-stc
  script:
    - ssh root@dds_stc ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/em-vm-creation.yml -v
  allow_failure: true
  when: manual
  
