stages:
  - copyrepotodds 
  - uploadsoftwaretocps
  - uploadsoftwaretoemm
  - emmplatformospatches
  - cpsplatformveritas
  - cpsplatform
  - cpsplatformhealthcheck
  - emmplatformveritas
  - emmplatform3pp
  - emmplatform
  - emmmasterhealthcheck
  - emmaddnode
  - emmworkerhealthcheck
  - mgrappinstall
  - mgrhealthcheck
  - mgrappaddnode
  - femappinstall
  - femhealthcheck
  - femappaddnode
  - olmappinstall
  - olmhealthcheck
  - olmappaddnode
  - emmcreatelogicalservers
  - emmcreateadditionalcomponents
  - systemhardening

.copyrepotodds:
  stage: copyrepotodds
  tags:
    - em-aip
  script:
    - hostname
    - pwd
    - ssh <dds user>@<dds hostname> 'hostname'
    - ssh <dds user>@<dds hostname> 'mkdir -p ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}'
    - scp -pr ./ENV_INFO/ ./HOST/ ./PLAYBOOK/ ./ROLES/ <dds user>@<dds hostname>:./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}
  #allow_failure: true
  when: manual

uploadsoftwaretocps:
  stage: uploadsoftwaretocps
  tags:
    - em-aip
  script:
     #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm_upload_software_to_cps.yml -v
     - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm_upload_software_to_cps.yml -v
  allow_failure: true
  when: manual

uploadsoftwaretoemm:
  stage: uploadsoftwaretoemm
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm_upload_software_to_emmnodes.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm_upload_software_to_emmnodes.yml -v
  allow_failure: true
  when: manual
  
emmplatformospatches:
  stage: emmplatformospatches
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm_apply_ospatches.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm_apply_ospatches.yml -v
  allow_failure: true
  when: manual 

cpsplatformveritas:
  stage: cpsplatformveritas
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-veritas-cps.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-veritas-cps.yml -v
  allow_failure: true
  when: manual

cpsplatforminstall:
  stage: cpsplatform
  tags:
    - em-aip
  script:
     #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-cps.yml -v
     - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps.yml -v
  allow_failure: true
  when: manual

cpshealthcheck:
  stage: cpsplatformhealthcheck
  tags:
    - em-aip
  script:
     #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-cps-healthcheck.yml -v
     - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-healthcheck.yml -v
  when: manual

emmplatformveritas:
  stage: emmplatformveritas
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-veritas.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-veritas.yml -v
  allow_failure: true
  when: manual 

emmplatform3pp:
  stage: emmplatform3pp
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-3pp.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-3pp.yml -v
  allow_failure: true
  when: manual

emmplatforminstall:
  stage: emmplatform
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-platform.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform.yml -v
  allow_failure: true
  when: manual

emmmasterhealthcheck:
  stage: emmmasterhealthcheck
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-master-healthcheck.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-master-healthcheck.yml -v
  when: manual

emmplatformaddnode:
  stage: emmaddnode
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-platform-addnode.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform-addnode.yml -v
  allow_failure: true
  when: manual

emmworkerhealthcheck:
  stage: emmworkerhealthcheck
  tags:
    - em-aip
  script:
     #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-worker-healthcheck.yml -v
     - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-worker-healthcheck.yml -v
  when: manual
  
mgrappinstall:
  stage: mgrappinstall
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-mgrapp.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp.yml -v
  allow_failure: true
  when: manual

mgrhealthcheck:
   stage: mgrhealthcheck
   tags:
    - em-aip
   script:
     #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-MGR-healthcheck.yml -v
     - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-MGR-healthcheck.yml -v
   when: manual
   
mgraddnode:
  stage: mgrappaddnode
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-mgrapp-addnode.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp-addnode.yml -v
  when: manual

femappinstall:
  stage: femappinstall
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-femapp.yml
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp.yml
  #allow_failure: true
  when: manual

femhealthcheck:
   stage: femhealthcheck
   tags:
    - em-aip
   script:
     #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-FEM-healthcheck.yml -v
     - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-FEM-healthcheck.yml -v
   when: manual
   
femaddnode:
  stage: femappaddnode
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-femapp-addnode.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp-addnode.yml -v
  when: manual 

olmappinstall:
  stage: olmappinstall
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-olmapp.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp.yml -v
  #allow_failure: true
  when: manual

olmhealthcheck:
  stage: olmhealthcheck
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-OLM-healthcheck.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-OLM-healthcheck.yml -v
  when: manual
  
olmaddnode:
  stage: olmappaddnode
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-olmapp-addnode.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp-addnode.yml -v
  when: manual

emmcreatelogicalservers:
  stage: emmcreatelogicalservers
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-create-logicalservers.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-create-logicalservers.yml -v
  when: manual

emmcreateadditionalcomponents:
  stage: emmcreateadditionalcomponents
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-create-additionalcomponents.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-create-additionalcomponents.yml -v
  when: manual

systemhardening:
  stage: systemhardening
  tags:
    - em-aip
  script:
    #- ssh <dds user>@<dds hostname> ansible-playbook -i ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/HOST/hosts ./DevOps/${CI_PROJECT_NAMESPACE}/${CI_COMMIT_BRANCH}/PLAYBOOK/emm-system-hardening.yml -v
    - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-system-hardening.yml -v
  allow_failure: true
  when: manual