stages:
  #- ansiblehost
  - cpsplatform
  - emmplatform
  - emmaddnode
  - mgrappinstall
  - mgrappaddnode
  - femappinstall
  - femappaddnode
  - olmappinstall
  - olmappaddnode
cpsplatforminstall:
     stage: cpsplatform
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master.yaml
     allow_failure: true
     when: manual
emmplatforminstall:
     stage: emmplatform
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform.yaml
     allow_failure: true
     when: manual
emmplatformaddnode:
     stage: emmaddnode
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform-addnode.yaml
     allow_failure: true
     when: manual
.mgrappinstall:
     stage: mgrappinstall
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp.yml
.femappinstall:
     stage: femappinstall
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp.yml
.olmappinstall:
     stage: olmappinstall
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp.yml

     