stages:
  #- ansiblehost
  - cpsplatform
  - cpsplatformhealthcheck
  - emmplatform
  - emmaddnode
  - mgrappinstall
  - mgrappaddnode
  - femappinstall
  - femappaddnode
  - olmappinstall
  - olmappaddnode
cpsplatforminstall:
     stage: cpsplatform
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master.yaml
     allow_failure: true
     when: manual
cpshealthcheck:
     stage: cpsplatformhealthcheck
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master-healthcheck.yaml

emmplatforminstall:
     stage: emmplatform
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform.yaml
     allow_failure: true
     when: manual
emmplatformaddnode:
     stage: emmaddnode
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform-addnode.yaml
     allow_failure: true
     when: manual
mgrappinstall:
     stage: mgrappinstall
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp.yml
     allow_failure: true
     when: manual
femappinstall:
     stage: femappinstall
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp.yml
     allow_failure: true
     when: manual
olmappinstall:
     stage: olmappinstall
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp.yml
     allow_failure: true
     when: manual

     