stages:
  #- ansiblehost
  - cpsplatform
  - cpsplatformhealthcheck
  - emmplatform
  - emmmasterhealthcheck
  - emmaddnode
  - emmworkerhealthcheck
  - mgrappinstall
  - mgrhealthcheck
  - mgrappaddnode
  - femappinstall
  - femhealthcheck
  - femappaddnode
  - olmappinstall
  - olmhealthcheck
  - olmappaddnode
cpsplatforminstall:
     stage: cpsplatform
     tags:
       - emm-cluster
     script:
        - cp ./ENV_INFO/cps1.yml ./ROLES/platform_cps1/vars/
        - cp ./ENV_INFO/cps2.yml ./ROLES/platform_cps2/vars/
        - cp ./ENV_INFO/cps3.yml ./ROLES/platform_cps3/vars/
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master.yaml -v
     allow_failure: true
     #when: manual
cpshealthcheck:
     stage: cpsplatformhealthcheck
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master-healthcheck.yaml -v
     #when: manual

emmplatforminstall:
     stage: emmplatform
     tags:
       - emm-cluster
     script:
       - cp ./ENV_INFO/emm-platform.yml ./ROLES/platform_emm/vars/emm.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform.yaml -v
     allow_failure: true
     #when: manual
emmmasterhealthcheck:
     stage: emmmasterhealthcheck
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-master-healthcheck.yaml -v
     #when: manual
     
emmplatformaddnode:
     stage: emmaddnode
     tags:
       - emm-cluster
     script:
       - cp ./ENV_INFO/emm-addnode.yml ./ROLES/platform_emm_addnode/vars/emm.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform-addnode.yaml -v
     allow_failure: true
     #when: manual
emmworkerhealthcheck:
     stage: emmworkerhealthcheck
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-worker-healthcheck.yaml -v
     #when: manual
mgrappinstall:
     stage: mgrappinstall
     tags:
       - emm-cluster
     script:
       - cp ./ENV_INFO/mgr.yml ./ROLES/app_MGR/vars/mgr.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp.yml -v
     allow_failure: true
     #when: manual
mgrhealthcheck:
      stage: mgrhealthcheck
      tags:
       - emm-cluster
      script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-MGR-healthcheck.yaml -v
      #when: manual
mgraddnode:
     stage: mgrappaddnode
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp-addnode.yml -v
     #when: manual       
femappinstall:
     stage: femappinstall
     tags:
       - emm-cluster
     script:
       - cp ./ENV_INFO/fem.yml ./ROLES/app_FEM/vars/fem.yml -v
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp.yml
     allow_failure: true
     #when: manual
femhealthcheck:
      stage: femhealthcheck
      tags:
       - emm-cluster
      script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-FEM-healthcheck.yaml -v
      #when: manual
femaddnode:
     stage: femappaddnode
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp-addnode.yml -v
     #when: manual 
olmappinstall:
     stage: olmappinstall
     tags:
       - emm-cluster
     script:
       - cp ./ENV_INFO/olm.yml ./ROLES/app_OLM/vars/olm.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp.yml -v
     allow_failure: true
     #when: manual
olmhealthcheck:
     stage: olmhealthcheck
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-OLM-healthcheck.yaml -v
     #when: manual
olmaddnode:
     stage: olmappaddnode
     tags:
       - emm-cluster
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp-addnode.yml -v
     #when: manual
     