stages:
  #- ansiblehost
  - cpsplatform
  - emmplatform
  - emmaddnode
  - mgrappinstall
  - mgrappaddnode
  - femappinstall
  - femappaddnode
  - olmappinstall
  - olmappaddnode
cpsplatforminstall:
     stage: cpsplatform
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master.yaml
emmplatforminstall:
     stage: emmplatform
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform.yaml
emmplatformaddnode:
     stage: emmaddnode
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform-addnode.yaml
mgrappinstall:
     stage: mgrappinstall
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp.yml
femappinstall:
     stage: femappinstall
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp.yml
olmappinstall:
     stage: femappinstall
     script:
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp.yml

     