stages:
  #- ansiblehost
  - cpsplatform
  - cpsplatformhealthcheck
  - emmplatform
  - emmaddnode
  - mgrappinstall
  - mgrappaddnode
  - femappinstall
  - femappaddnode
  - olmappinstall
  - olmappaddnode
cpsplatforminstall:
     stage: cpsplatform
     tags:
       - emm-cluster
     script:
        - cp ./ENV-INFO/cps1.yml ./ROLES/platform_cps1/vars/
        - cp ./ENV-INFO/cps2.yml ./ROLES/platform_cps2/vars/
        - cp ./ENV-INFO/cps3.yml ./ROLES/platform_cps3/vars/
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master.yaml
     allow_failure: true
     when: manual
cpshealthcheck:
     stage: cpsplatformhealthcheck
     tags:
       - emm-cluster
     script:
        - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-cps-master-healthcheck.yaml

emmplatforminstall:
     stage: emmplatform
     tags:
       - emm-cluster
     script:
       - cp ./ENV-INFO/emm-platform.yml ./ROLES/platform_emm/vars/emm.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform.yaml
     allow_failure: true
     when: manual
emmplatformaddnode:
     stage: emmaddnode
     tags:
       - emm-cluster
     script:
       - cp ./ENV-INFO/emm-addnode.yml ./ROLES/platform_emm_addnode/vars/emm.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-platform-addnode.yaml
     allow_failure: true
     when: manual
mgrappinstall:
     stage: mgrappinstall
     tags:
       - emm-cluster
     script:
       - cp ./ENV-INFO/mgr.yml ./ROLES/app_MGR/vars/mgr.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-mgrapp.yml
     allow_failure: true
     when: manual
femappinstall:
     stage: femappinstall
     tags:
       - emm-cluster
     script:
       - cp ./ENV-INFO/fem.yml ./ROLES/app_FEM/vars/fem.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-femapp.yml
     allow_failure: true
     when: manual
olmappinstall:
     stage: olmappinstall
     tags:
       - emm-cluster
     script:
       - cp ./ENV-INFO/olm.yml ./ROLES/app_OLM/vars/olm.yml
       - ansible-playbook -i ./HOST/hosts ./PLAYBOOK/emm-olmapp.yml
     allow_failure: true
     when: manual

     