---
# tasks file for platform_cps
- name: Load variable file
  include_vars: emm.yml
- name: Get EM20 Installation Tool version
  shell: ls -td CXP* | head -1
  register: version  
- name: Go to template path & create platform nfs ini
  shell:
    chdir: ./{{ version.stdout }}/templates/Linux
    cmd: cp platform_addnode.ini.eric platform_addnode.ini
- name: Update the hostname
  hostname: name=emm2-001
- name: Copy the platform script
  copy: src=Install_Platform.sh dest=./{{ version.stdout }}/
  backup: yes
- name: Copy hosts file
  copy: src=hosts dest=/etc/hosts
  backup: yes
- name: Update the cps ini file for ONM Bond
  ini_file:
    path: ./{{ version.stdout }}/templates/Linux/platform_addnode.ini
    section: ONM Bond
    option: bonding_interface_primary_ONM
    value: "{{ bonding_interface_primary_ONM }}"
    no_extra_spaces: yes
- name: Update the nfs ini file for Interface IP
  ini_file:
    path: ./{{ version.stdout }}/templates/Linux/platform_addnode.ini
    section: Interface IP
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {bonding_interface_ip_ONM: "{{ bonding_interface_ip_ONM }}",netmask_ONM: "{{ netmask_ONM }}",default_gateway_ip_ONM: "{{ default_gateway_ip_ONM }}"}
- name: Update the nfs ini file for CLUSTER
  ini_file:
    path: ./{{ version.stdout }}/templates/Linux/platform_addnode.ini
    section: Cluster
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {Clus_Node_IP: "{{ Clus_Node_IP }}",HeartBeat_Link_1: "{{ HeartBeat_Link_1 }}",HeartBeat_Link_2: "{{ HeartBeat_Link_2 }}"}
- name: Copy automation script
  copy: src=install_updated.sh dest=/{{ version.stdout }}/install_addnode.sh
- name: Execute the EMM Addnode platform script
  shell: sudo sh /{{ version.stdout }}/install_addnode.sh
  ignore_errors: true
  ignore_unreachable: true
    
 
