---
  # tasks file
  - name: Load enviroment file
    include_vars: ../ENV_INFO/emm.yml
  - name: Get EM20 Installation Tool version
    shell: ls -td {{ working_dir }}/CXP* | head -1
    register: version
  - name: Cleanup CMP directory if already exists
    file:
      path: "{{ version.stdout }}/CMP"
      state: absent
  - name: Copy Additional Components configuration
    copy: src="../ENV_INFO/CMP" dest={{ version.stdout }}/
  - name: Get .in files
    shell: ls ./CMP/*.in
    register: in_file
    args:
      chdir: '{{ version.stdout }}'
  - name: Create additional Components - check logs in /var/adm/MM_LOGS - or connect with "screen -x DEVOPS" in master node
    shell: screen -S DEVOPS sh -c "cat {{ item }} | sudo -E ./MM_UTILITY"    
    with_items: '{{ in_file.stdout_lines}}'
    args:
      chdir: '{{ version.stdout }}'
    environment:
      ACTIVITY_TYPE: '{{ ACTIVITY_TYPE }}'
    ignore_errors: yes
