- name: Load variable file
  include_vars: ../ENV_INFO/emm.yml

- name: Create mount directory for iso1
  file:
    path: /cdrom/rhel_os
    state: directory
  
#- name: change permissions to  rhel_os directory
#  file:
#     path: /cdrom/rhel_os
#     owner: "{{user}}"
#     group: "{{user}}"
#     mode: 0755
  
- name: Create mount directory for iso3
  file:
    path: /cdrom/sw_3pp
    state: directory
  
#- name: change permissions to  sw_3pp directory
#  file:
#     path: /cdrom/sw_3pp
#     owner: "{{user}}"
#     group: "{{user}}"
#     mode: 0755

- name: Find threepp iso file
  find:
    paths: "{{ working_dir }}"      
    patterns: "19089-CXP*_3*.iso"
  register: threepp_iso

- name: Mount iso file {{ threepp_iso.files[0].path }}
  mount:
    src: '{{ threepp_iso.files[0].path }}'
    path: /cdrom/sw_3pp
    fstype: iso9660
    opts: loop,ro
    state: mounted

- name: check Mount iso file {{ threepp_iso.files[0].path }}
  command: df -kh
  
- name: Create symlink to repository
  file:
    src: /cdrom/sw_3pp/OS_PATCH/RHEL7/rhel7_errata.repo
    dest: /etc/yum.repos.d/rhel7_errata.repo
    state: link
 
  
- name: Clean the repositories
  command: yum clean all
  args:
    warn: no
    
- name: Install OS patches - check /var/log/yum.log
  yum:
    name: '*'
    state: latest
  register: os_patch_result

- name: Umount iso file
  mount:
    src: '{{ threepp_iso.files[0].path }}'
    path: /cdrom/sw_3pp
    fstype: iso9660
    opts: loop,ro
    state: absent
      
- name: Rebooting the system
  block:
    - name: Rebooting the system
      reboot:
        reboot_timeout: 900
    - name: Wait for the server to come up
      wait_for_connection:
        timeout: 600
        delay: 90
        sleep: 20
  when: os_patch_result.changed

- name: Delete sysmlink to the repository
  file:
    dest: sudo /etc/yum.repos.d/rhel7_errata.repo
    state: absent
  

- name: Remove older kernel version - get kernel versions with uname -r or rpm -q kernel
  yum:
    name: '{{ old_kernel }}'
    state: absent    

- name: Verifying uname Installation
  command: uname -a
  
- name: Verifying OS Installation
  command: cat /etc/redhat-release
  