---
# tasks file for platform_cps
- name: Go to template path & create cps ini
  shell:
    chdir: /install/CXP9034012_R8S/templates/Linux
    cmd: cp platform_cps.ini.eric platform_cps.ini
- name: Copy the platform script
  copy: src=Install_Platform.sh dest=/install/CXP9034012_R8S/
- name: Update the cps ini file for ONM Bond
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cps.ini
    section: ONM Bond
    option: bonding_interface_primary_ONM
    value: "{{CPS1.ONM Bond.bonding_interface_primary_ONM}}"
    no_extra_spaces: yes
    #with_dict: "{{ CPS1 }}"
- name: Update the cps ini file for Interface IP
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cps.ini
    section: Interface IP
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {bonding_interface_ip_ONM: 192.168.50.10,netmask_ONM: 255.255.255.0,default_gateway_ip_ONM: 192.168.50.1}
- name: Update the cps ini file for CLUSTER
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cps.ini
    section: Cluster
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {cps_virtual_IP: 192.168.50.11,other_hosts_ONM: 192.168.50.14}
- name: Execute the CPS platform script
  shell: sh /opt/install_updated.sh
    
 
