---
  # tasks file
  - name: Load variable file
    include_vars: ../../../ENV_INFO/emm.yml

  - name: INFO about Automatic Hardening in CPS
    debug:
      msg: "Hardening Automation requires java which is not installed in stardand EM. Please follow CPI instructions to configure Manually in CPS"

  - name: Get EM20 Installation Tool version
    shell: ls -td {{ working_dir }}/CXP* | head -1
    register: version

  - name: Create directory '{{ version.stdout }}'/SH
    file:
      path: "{{ version.stdout }}/SH"
      state: directory
      mode: '0777'

  - name: Stop cluster services
    shell: sudo /opt/VRTSvcs/bin/hastop -all

  - pause:
     minutes: 5

  - name: Copy MMUtilityClient.jar
    copy: src=MMUtilityClient.jar dest={{ version.stdout }}/SH/MMUtilityClient.jar

  - name: Copy SYSTEM_HARDENING.in
    copy: src=../../../ENV_INFO/SH/System_Hardening.in dest={{ version.stdout }}/SH/System_Hardening.in
    register: output

  - name: Backup MM_Harden.ini
    shell: sudo mv {{ version.stdout }}/templates/Linux/MM_Harden.ini {{ version.stdout }}/templates/Linux/MM_Harden.ini_original_{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}
    register: output

  - name: Copy MM_Harden.ini
    copy: src=../../../ENV_INFO/SH/MM_Harden.ini dest={{ version.stdout }}/templates/Linux/MM_Harden.ini
    register: output

  - name: retrieve the list of System_Hardening params
    shell:
      cmd: cat {{ version.stdout }}/SH/System_Hardening.in
    register: file_lines

  - name: Execute the MMUtility for System Hardening
    shell:
      cmd: /usr/java/jre/bin/java -jar ./SH/MMUtilityClient.jar {{ item }}
    register: moutput
    loop: "{{ file_lines.stdout_lines }}"
    args:
      chdir: '{{ version.stdout }}'
    ignore_errors: true

  - name: Start cluster services
    shell: sudo /opt/VRTSvcs/bin/hastart

  - name: Show cluster status
    shell: sudo /opt/VRTSvcs/bin/hastatus -sum