---
# tasks file for mgr
- name: Load variable file
  include_vars: mgr.yml
- name: Get EM20 Installation Tool version
  shell: ls -td CXP* | head -1
  register: version  
- name: Go to template path & create platform nfs ini
  shell:
    chdir: ./{{ version.stdout }}/templates/Linux
    cmd: cp config_template_MGR.eric config_template_MGR.ini
- name: Copy the app installation script
  copy: src=Install_App.sh dest=./{{ version.stdout }}/ backup=yes
- name: Update the nfs ini file for Interface IP
  ini_file:
    path: ./{{ version.stdout }}/templates/Linux/config_template_MGR.ini
    section: null
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {MANAGER_PG_DB_USER: "{{ MANAGER_PG_DB_USER }}",MANAGER_PG_DB_PASSWD: "{{ MANAGER_PG_DB_PASSWD }}",MANAGER_PG_DB_Port: "{{ MANAGER_PG_DB_Port }}",Manager_IP: "{{ Manager_IP }}",Manager_Netmask: "{{ Manager_Netmask }}",LIC_IP: "{{ LIC_IP }}",LIC_Netmask: "{{ LIC_Netmask }}"}
- name: Copy automation script
  copy: src=install_MGR.sh dest=./{{ version.stdout }}/install_MGR.sh mode=u+rwx
- name: Execute the MGR App Installation script
  shell: sudo sh ./{{ version.stdout }}/install_MGR.sh
    
 
