---
# tasks for veritas installation on EMM nodes
- name: Load variable file
  include_vars: ../ENV_INFO/emm.yml

- name: Get EM20 Installation Tool version
  shell: ls -td {{ working_dir}}/CXP* | head -1
  register: version  

- name: Copy automation script
  copy: src=emm_install_3pp.sh dest={{ version.stdout }}/emm_install_3pp.sh mode=u+rwx

- name: Execute the 3PP Installation script for {{ deployment }} deployment - check logs in /var/adm/MM_LOGS/3pp
  shell: sh ./emm_install_3pp.sh {{ deployment }}
  args:
    chdir: '{{ version.stdout }}'
  ignore_errors: no
  ignore_unreachable: no
  
