---
  # tasks file
  - name: Load enviroment file
    include_vars: ../ENV_INFO/emm.yml
  - name: Get EM20 Installation Tool version
    shell: ls -td {{ working_dir }}/CXP* | head -1
    register: version
  - name: Copy Logical Servers configuration
    copy: src="../ENV_INFO/LS" dest={{ version.stdout }}/ mode=755
  - name: Get .in files
    shell: ls {{ version.stdout }}/LS/*.in
    register: in_file
  - name: Create additional Logical Servers - check logs in /var/adm/MM_LOGS
    shell: "cat {{ item }} | sudo -E ./MM_UTILITY"
    with_items: '{{ in_file.stdout_lines}}'
    args:
     chdir: '{{ version.stdout }}'