---
- name: Load variable file
  include_vars: ../ENV_INFO/emm.yml

- name: Create directory '{{ working_dir }}'
  file:
    path: '{{ working_dir }}'
    state: directory
    mode: '0777' 
    
#- name: change permissions to working_dir directory
#  file:
#    path: '{{ working_dir }}'
#    owner: "{{user}}"
#    group: "{{user}}"
#    mode: '0755'

#- name: Copy SW - Redhat
#  copy:
#    src: "{{ emm_media_src_dir }}/{{ redhat_sw }}"
#    dest: "{{ working_dir }}"
#    force: no

- name: Copy SW - Infoscale
  copy:
    src: "{{ emm_media_src_dir }}/{{ infoscale_sw }}"
    dest: "{{ working_dir }}"
    force: no

- name: Copy SW - 3PPs
  copy:
    src: "{{ emm_media_src_dir }}/{{ threepp_sw }}"
    dest: "{{ working_dir }}"
    force: no

- name: Copy SW - tools
  copy:
    src: "{{ emm_media_src_dir }}/{{ tool_sw }}"
    dest: "{{ working_dir }}"
    force: no


- name: Uncompress SW
  shell: unzip -o {{ infoscale_sw }};  unzip -o {{ tool_sw }}; unzip -o {{ threepp_sw }}; tar -xvf *.tar
  args:
    chdir: '{{ working_dir }}'
    

### Find zip and tar files
- name: Find zip and tar files
  find:
    paths: "{{ working_dir }}"      
    patterns: "*.zip,*.tar"
  register: find_result

### Delete all zip and tar files
- name: Delete zip and tar files
  file: 
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ find_result.files }}"

- name: Give permissions to working directory
  file: 
    path: "{{ working_dir }}"
    state: directory
    mode: '0777'
    recurse: yes
  #become: yes
