---
# tasks for veritas installation on EMM nodes
- name: Load variable file
  include_vars: ../ENV_INFO/emm.yml

- name: Get EM20 Installation Tool version
  shell: ls -td {{ working_dir}}/CXP* | head -1
  register: version  

- name: Copy automation script
  copy: src=emm_install_veritas.sh dest={{ version.stdout }}/emm_install_veritas.sh mode=u+rwx

- name: Execute the Veritas Installation script - check logs in /var/adm/MM_LOGS
  shell: sh ./emm_install_veritas.sh {{ veritas }}
  args:
    chdir: '{{ version.stdout }}'
  ignore_errors: yes
  ignore_unreachable: no
  
- name: Verifying Veritas InfoScale Software Deployment
  shell: rpm -qa | grep VRTS
