---
# tasks file for platform_cps
- name: Load variable file
  include_vars: cps1.yml
- name: Go to template path & create cps ini
  shell:
    chdir: /install/CXP9034012_R8S/templates/Linux
    cmd: cp platform_cps.ini.eric platform_cps.ini
- name: Copy the platform script
  copy: src=Install_Platform.sh dest=/install/CXP9034012_R8S/
- name: Update the cps ini file for ONM Bond
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cps.ini
    section: ONM Bond
    option: bonding_interface_primary_ONM
    value: "{{ bonding_interface_primary_ONM }}"
    no_extra_spaces: yes
- name: Update the cps ini file for Interface IP
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cps.ini
    section: Interface IP
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {bonding_interface_ip_ONM: "{{ bonding_interface_ip_ONM }}",netmask_ONM: "{{ netmask_ONM }}",default_gateway_ip_ONM: "{{ default_gateway_ip_ONM }}"}
- name: Update the cps ini file for CLUSTER
  ini_file:
    path: /install/CXP9034012_R8S/templates/Linux/platform_cps.ini
    section: Cluster
    option: "{{item.key}}"
    value: "{{item.value}}"
    no_extra_spaces: yes
  with_dict: {cps_virtual_IP: "{{ cps_virtual_IP }}",other_hosts_ONM: "{{ other_hosts_ONM }}"}
- name: Copy automation script
  copy: src=install_updated.sh dest=/opt/
- name: Execute the CPS platform script
  shell: sh /opt/install_updated.sh
    
 
